### ISSUE TITLE
code/login_manager

### ISSUE THREAD

**Issue by ayratmsk** [thebracket/ArdanUltimateRust-5Days#1]
I guess, while add_user sleeve checking in main(), asking admin.is_some() not a good option
Cause new user with any --admin flag become admin that way
a) cargo run -- add --admin true fred password
b) cargo run -- add --admin false fred password

**Comment by thebracket** [comment]
I agree. Since the video is recorded, it's a tough one to change until the next refresh. I've updated the repo to use `unwrap_or(false)` instead of `is_some()` - which gives the desired behavior.

**Comment by thebracket** [comment]
(Closing issue)
